zitadel/typescript

- acceptance/setup.sh
- acceptance/zitadel.yaml
> chore: setup human admin on localhost

- apps/login/app/(login)/accounts/page.tsx
- apps/login/app/session/route.ts
- apps/login/lib/zitadel.ts
- apps/login/ui/SessionItem.tsx
- apps/login/ui/SessionsList.tsx
- apps/login/utils/cookies.ts
- packages/zitadel-server/src/index.ts
> feat: account switcher, delete account

- apps/login/app/(login)/passkey/login/page.tsx
- apps/login/app/passkeys/route.ts
- apps/login/app/session/route.ts
- apps/login/lib/zitadel.ts
- apps/login/ui/LoginPasskey.tsx
- apps/login/ui/RegisterPasskey.tsx
> feat: login with passkey

- README.md
- apps/login/app/page.tsx
- apps/login/lib/demos.ts
> Deploy to vercel

- README.md
> docs: add login features to readme

- .github/workflows/test.yml
- package.json
> chore: upgrade pnpm to latest stable version

- README.md
Update readme with the implemented features of the login
> docs: update readme with implemented features

- packages/zitadel-client2/package.json
- packages/zitadel-node/.eslintrc.cjs
- packages/zitadel-node/package.json
- packages/zitadel-node/src/index.ts
- packages/zitadel-node/tsconfig.json
- packages/zitadel-node/tsup.config.ts
- packages/zitadel-node/turbo.json
- pnpm-lock.yaml
Related to https://github.com/zitadel/typescript/pull/63 this will be the package used to create transports in the Node (server) environment
> feat: add @zitadel/node pkg

- .github/workflows/issues.yml
> fix: update action version

- README.md
- apps/login/src/lib/zitadel.ts
fixes the cache if no env is set
> fix: cache fallback

- .github/workflows/test.yml
- packages/zitadel-client/package.json
- packages/zitadel-client/src/interceptors.test.ts
- packages/zitadel-node/package.json
- pnpm-lock.yaml
- Fixing some warning
```
package.json:11:6:
11 │       "types": "./dist/index.d.ts"
╵       ~~~~~~~
The "import" condition comes earlier and will be used for all "import" statements:
package.json:9:6:
9 │       "import": "./dist/index.js",
╵       ~~~~~~~~
The "require" condition comes earlier and will be used for all "require" calls:
package.json:10:6:
10 │       "require": "./dist/index.cjs",
╵       ~~~~~~~~~
```
> chore: enable unit tests

- apps/login/readme.md
- apps/login/src/lib/server/cookie.ts
- apps/login/src/lib/server/otp.ts
- apps/login/src/lib/server/password.ts
- apps/login/src/lib/server/register.ts
- apps/login/src/lib/server/session.ts
- apps/login/src/lib/zitadel.ts
- packages/zitadel-client/src/index.ts
This PR implements lifetime settings from loginSettings. Sessions now have varying durations based on the user's resource owner and its associated settings.
> feat: Implement Lifetimes for sessions

- apps/login/src/app/(login)/layout.tsx
- apps/login/src/app/(login)/register/page.tsx
- apps/login/src/components/language-provider.tsx
- apps/login/src/components/register-form.tsx
- apps/login/src/components/skeleton.tsx
- apps/login/src/lib/zitadel.ts
- apps/login/src/styles/globals.scss
> Promote qa to prod: session lifetimes

- acceptance/sink/go.mod
- acceptance/tests/login.ts
- acceptance/tests/register.spec.ts
- acceptance/tests/register.ts
- acceptance/tests/user.ts
- acceptance/tests/username-passkey.spec.ts
- acceptance/tests/username-password-changed.spec.ts
- acceptance/tests/username-password-otp_email.spec.ts
- acceptance/tests/username-password-otp_sms.spec.ts
- acceptance/tests/username-password-set.spec.ts
- acceptance/tests/username-password-totp.spec.ts
- acceptance/tests/username-password.spec.ts
- acceptance/tests/zitadel.ts
- package.json
- pnpm-lock.yaml
> chore: add totp acceptance tests

- apps/login/src/app/(login)/otp/[method]/page.tsx
- apps/login/src/components/login-otp.tsx
- apps/login/src/components/login-passkey.tsx
- apps/login/src/lib/cookies.ts
- apps/login/src/lib/server/session.ts
> fix: otp template url, improve error handling

- apps/login/readme.md
- apps/login/src/app/(login)/otp/[method]/page.tsx
- apps/login/src/app/login/route.ts
- apps/login/src/components/change-password-form.tsx
- apps/login/src/components/login-otp.tsx
- apps/login/src/components/session-item.tsx
- apps/login/src/components/sessions-list.tsx
- apps/login/src/components/set-password-form.tsx
- apps/login/src/lib/server/email.ts
- apps/login/src/lib/server/session.ts
- apps/login/src/lib/zitadel.ts
This PR improves session checks behind the `/login` endpoint. When navigating through the login or choosing an account, its validity is checked (loginSettings, expiration date, valid factors).
It also fixes minor bugs in session list and totp verification components.
> Promote qa to prod: OIDC fixes

- apps/login/src/app/login/route.ts
This removes a line which throws an unintended error when deserializing
> fix: remove `JSON.stringify` as log

- apps/login/src/app/(login)/verify/page.tsx
- apps/login/src/lib/server/verify.ts
- apps/login/src/lib/zitadel.ts
- packages/zitadel-proto/package.json
> send code on verify page visit, generate from branch

- packages/zitadel-client/CHANGELOG.md
- packages/zitadel-client/package.json
- packages/zitadel-proto/CHANGELOG.md
- packages/zitadel-proto/package.json
version 1.0.2 of `@zitadel/client` and `@zitadel/proto`
> publish /client and /proto v1.0.2

- apps/login/package.json
- pnpm-lock.yaml
> chore(deps): update next canary

- .changeset/yellow-squids-brake.md
- README.md
> fix(@zitadel/client): nodenext module resolution, change readme to highlight beta state

- package.json
Fixes https://github.com/zitadel/typescript/actions/runs/13328140098/job/37225887552
> chore: fix docker pipeline

- apps/login/src/app/(login)/verify/page.tsx
- apps/login/src/components/login-otp.tsx
- apps/login/src/lib/server/idp.ts
- apps/login/src/lib/server/invite.ts
- apps/login/src/lib/server/loginname.ts
- apps/login/src/lib/server/password.ts
- apps/login/src/lib/server/verify.ts
This PR adds the basepath to absolute urls for email verification, otp, and other use cases.
> fix: basepath for absolute urls

- apps/login/locales/pl.json
- apps/login/src/lib/i18n.ts
> feat: internationalization Polish

- .github/workflows/docker.yml
> Feature: linux/arm64 platform for login package

- .changeset/red-owls-battle.md
- packages/zitadel-client/CHANGELOG.md
- packages/zitadel-client/package.json
- packages/zitadel-proto/CHANGELOG.md
- packages/zitadel-proto/package.json
- packages/zitadel-proto/turbo.json
> Version packages 1.2.0

- apps/login/turbo.json
> fix: turbo dep

- apps/login/src/app/(login)/device/consent/page.tsx
- apps/login/src/app/(login)/device/page.tsx
- apps/login/src/components/consent.tsx
This incorporates smaller UI changes
> promote qa to prod
