zitadel/typescript

.github/workflows/issues.yml

automatically ad prs of non engineers to board and label community prs

chore: add workflow for issues and prs to pm board

---

apps/login/src/app/api/loginname/route.ts
apps/login/src/app/login/route.ts
apps/login/src/lib/zitadel.ts
packages/zitadel-client/src/v3alpha.ts

This PR adds org discovery on register. If a user enters an email for login, orgs are searched according to the suffix of the email if no user was found and the user is redirected to the register page of the detected organization.
Closes #81

Promote qa to prod

---

apps/login/src/app/(login)/mfa/page.tsx
apps/login/src/app/(login)/mfa/set/page.tsx
apps/login/src/app/(login)/otp/[method]/page.tsx
apps/login/src/app/(login)/otp/[method]/set/page.tsx
apps/login/src/app/(login)/passkey/page.tsx
apps/login/src/app/(login)/passkey/set/page.tsx
apps/login/src/app/(login)/password/change/page.tsx
apps/login/src/app/(login)/password/page.tsx
apps/login/src/app/(login)/password/set/page.tsx
apps/login/src/app/(login)/u2f/page.tsx
apps/login/src/app/(login)/u2f/set/page.tsx
apps/login/src/app/(login)/verify/page.tsx
apps/login/src/components/login-otp.tsx
apps/login/src/components/password-form.tsx
apps/login/src/components/set-password-form.tsx
apps/login/src/lib/server/password.ts
apps/login/src/lib/zitadel.ts

This PR changes the urlTemplate of the mail to use the host of the deployment and fixes unavailable translation keys

fix: use urlTemplate for reset password mail, fix error namespace for i18n

---

.github/workflows/test.yml

The Cypress binary is only available when the pnpm dependencies cache is not hit, aka when pnpm install actually downloads dependencies. The problem is that a postinstall hook downloads the Cypress binary, which is not triggered when the dependencies are loaded from cache.
The solution is to cache the Cypress binary along with the pnpm dependencies.

chore(test:integration): install cypress binary

---

apps/login/cypress/integration/login.cy.ts
apps/login/src/app/(login)/authenticator/set/page.tsx
apps/login/src/app/(login)/idp/[provider]/success/page.tsx
apps/login/src/app/(login)/loginname/page.tsx
apps/login/src/app/(login)/otp/[method]/page.tsx
apps/login/src/components/login-otp.tsx
apps/login/src/components/password-form.tsx
apps/login/src/components/session-item.tsx
apps/login/src/components/sign-in-with-idp.tsx
apps/login/src/components/username-form.tsx
apps/login/src/lib/client.ts
apps/login/src/lib/server/loginname.ts
apps/login/src/lib/server/password.ts
apps/login/src/lib/zitadel.ts

These features / fixes are implemented with this PR
- password change required is handled now. after a user password is checked, and if change is required, a user will be redirected to `/password/change`
- an additional check for force MFA is done, after checking a user password. If either forceMFA or forceLocalMFA is enforced, a user is prompted to setup MFA after password verification
- a password reset link now includes the authRequest if the flow was initiated with it 
- OTP links redirect to the same host where the flow was initiated and include the authRequest
- A user invitation can now be linked to an IDP
- if phone / email login is disabled, user results are removed where the input equals the disabled method
- If passkeys / password is disabled, throw an error.
- Check user …

additional login settings

---

.github/workflows/test.yml

Acceptance tests with "test:acceptance:prod" run against QA. The reason is that the bash logical operators aren't evaluated as expected.
To fix this, we explicitly test the command in an if condition.
Completes #303 
Contributes to #51

chore(acceptance): use prod secret on command test:acceptance:prod

---

README.md
apps/login/readme.md
apps/login/src/app/(login)/idp/[provider]/success/page.tsx
apps/login/src/app/(login)/loginname/page.tsx
apps/login/src/app/login/route.ts
apps/login/src/components/idp-signin.tsx
apps/login/src/lib/server/cookie.ts
apps/login/src/lib/server/session.ts
apps/login/src/lib/zitadel.ts

This PR adds the OIDC authRequestId context to the IDP flow and fixes the callback after login, linking an register with IDP. It also implements domain discovery for the IDP flow.

fix: Finish IDP Signup for OIDC flow

---

.changeset/fluffy-berries-thank.md
.github/workflows/release.yml
.github/workflows/test.yml
package.json
packages/zitadel-client/src/node.ts

This PR adds an export utility to use grpc-web in browser environments
Fixes the version mismatch in `release.yml` and `package.json`

fix: add grpc-web transport, fix release pnpm version

---

apps/login/src/app/(login)/idp/[provider]/failure/page.tsx
apps/login/src/components/choose-authenticator-to-login.tsx
apps/login/src/lib/server/loginname.ts

fix(login): provide alternative auth methods when IDP failure page is shown

---

.changeset/shiny-islands-sparkle.md
packages/zitadel-client/package.json
packages/zitadel-client/src/node.ts
packages/zitadel-client/src/web.ts
packages/zitadel-client/tsup.config.ts

this moves grpc web transport to the import path /web to avoid issues on browser runtimes.

fix(@zitadel/client): grpc web transport export

---

.nvmrc
CONTRIBUTING.md
apps/login/package.json
package.json
packages/zitadel-client/src/index.ts
packages/zitadel-client/src/interceptors.test.ts
packages/zitadel-client/src/node.ts
packages/zitadel-client/src/v1.ts
packages/zitadel-client/src/v2.ts
packages/zitadel-client/src/v3alpha.ts
packages/zitadel-client/src/web.ts
packages/zitadel-proto/buf.gen.yaml
packages/zitadel-tsconfig/tsup.json
pnpm-lock.yaml

While the `@zitadel/client` package might work perfectly in `moduleResolution: Bundler` based packages, that is not the case with `moduleResolution: nodenext`. The imports in declaration (`.d.ts`) files generated by tsup do not include the `.js` extension, which is required for successful resolution.
The solution was to add the extension to all files in the package. To make sure that the extension is required, I have removed `moduleResolution: Bundler` from the tsup tsconfig file (letting it fall back on the node20 tsconfig file). I have also removed `module: preserve`, as without `moduleResolution: Bundler`, type imports were failing (same as for me when I tried using `@zitadel/client` in my package). I noticed this in the `interceptors.ts` file, where the `Header` type resolved to …

fix(@zitadel/client): broken imports in projects using node16/nodenext module resolution

---

apps/login/next-env-vars.d.ts
apps/login/src/lib/service.ts
turbo.json

Allows configuring custom request headers for all outgoing gRPC connections.

feat: allow configuring custom request headers

---

.github/workflows/docker.yml
.github/workflows/test.yml

We provide the login at /ui/v2/login

chore(docker): use better base path

---

apps/login/src/middleware.ts

For self hosters, saml endpoints need to be proxied through the middleware. This PR adds the required domains to the middlware matcher function.

fix(SAML): add saml paths to proxy

---

apps/login/src/app/login/route.ts
apps/login/src/lib/oidc.ts
apps/login/src/lib/saml.ts
apps/login/src/lib/service.ts

This PR changes the behaviour of the login route (which is responsible to handle OIDC and SAML requests) to use the host header instead of the request.url to construct any further redirects. 
Note: This is essential in a docker environment behind a reverse proxy but not for vercel deployments

fix: construct url using host

---

apps/login/src/app/login/route.ts

This fixes the serializing function that creates the requestId from the samlRequest on the `/login` route

fix(saml): requestId serializing

---

.github/workflows/docker.yml

This PR aims to fix the Docker build pipeline by ensuring that any required stubs are generated before the Docker build step is executed.
- Inserted a "Generate stubs" step that runs "pnpm generate" before building for Docker.

chore: fix docker build pipeline

---

apps/login/src/components/session-item.tsx

Configures Moment.js [internationalization](https://momentjs.com/docs/#/i18n/) for all locales.
Since Moment.js supports multiple Chinese [variants](https://github.com/moment/moment/tree/develop/src/locale), this PR maps `zh` to `zh-cn` to ensure the correct locale is used.

feat: configure internationalization for Moment.js

---

apps/login/constants/csp.js
apps/login/mock/initial-stubs/zitadel.settings.v2.SettingsService.json
apps/login/next.config.mjs
apps/login/src/app/(login)/authenticator/set/page.tsx
apps/login/src/app/login/route.ts
apps/login/src/lib/cookies.ts
apps/login/src/lib/csp.ts
apps/login/src/lib/server/cookie.ts
apps/login/src/lib/server/session.ts
apps/login/src/lib/zitadel.ts
apps/login/src/middleware.ts

Closes #427 
This PR adds support for security settings, especially the i-frame options. It sets the headers according to https://zitadel.com/docs/guides/solution-scenarios/configurations#embedding-zitadel-in-an-iframe
on the pages: `/.well-known/:path*`,`/oauth/:path*`,`/oidc/:path*`,`/idps/callback/:path*`,`/saml/:path*` and the endpoint which redirects back from the OIDC `none` prompt.

fix(security-settings): override csp for allowed iframe

---

apps/login/src/lib/cookies.ts
turbo.json

This PR enforces secure cookies on production environments, especially if sameSite property is set to `none` which is required for the iFrame options.

fix: enfore secure cookie for production environments
